apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demarca-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
