apiVersion: v1
data:
  CORE_DATABASE_URL: cG9zdGdyZXM6Ly91ZGE1OGNnaXU5dHVrNjpwNTAxMGRhMGIzM2RlMWFhZDEyM2ZiMDZjZmU3MmY2ZDhiOGNmNjkxN2Y5NjhiNThjODlkZDYwOTAwODA2ZTM2MkBjYmVjNDU4NjlwNGpidS5jbHVzdGVyLWN6cnM4a2o0aXNnNy51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb206NTQzMi9kNjZpMnRqOTIyN2M4Nw==
  CORE_DB_HOST: ZGF0YWJhc2UtMS5jc2o0bzJjbWEwaDgudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  CORE_DB_NAME: ZGVtYXJjYQ==
  CORE_DB_PASSWORD: U2Fvb2RpUkRTMjAyNCE=
  CORE_DB_PORT: NTQzMg==
  CORE_DB_USER: cG9zdGdyZXM=
  CORE_DEBUG: VHJ1ZQ==
  CORE_INFOSIMPLES_TOKEN: NU5FckZEck9mVW9nZ1Rxa25zSmFSb1RkeW1BSm01cGxtWm5nM2Nkdg==
  CORE_Isaac: eUl5TDFhQ09zNDdPWEFleWhDMklwdDBSSGhBQmRia0JuNG5wbXNuRw==
  CORE_Jussara: NU5FckZEck9mVW9nZ1Rxa25zSmFSb1RkeW1BSm01cGxtWm5nM2Nkdg==
  CORE_REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  CORE_SECRET_KEY: c3VhLWNoYXZlLXNlY3JldGEtYXF1aQ==
  CORE_Z_API_CLIENT_TOKEN: RmFjNDBkMTIyMjA4MTRlZGJhMjFiNzBmY2RlZDc2OGI1Uw==
  CORE_Z_API_INSTANCE: M0UxMEJFNEUyQjFFNjA2MTQ0NDhCQUNGQ0FERTE1NTM=
  CORE_Z_API_TOKEN: QzMzM0VDNTU2MDQ1RjdENjg4OEY0QjM0
  NGROK_URL: MDkyNi0xNzktMjM2LTEzNy0yMzEubmdyb2stZnJlZS5hcHA=
  OPENAI_API_KEY: c2stcHJvai1WZHZXM3V2dGJvbEwtN1c5Z0JSS29xMVcxNUJnbGUtdjJ6eGlYQWlWM3pMdFY1YmpjWEc4aDZtcHFHWW5hWlJOOUlxWEExY0FYclQzQmxia0ZKMFdObTB4TV9kYkttZ0FxVFFXdUFyeDVkLXRsaS1pdFJqOU5zZUNzamhwdFpHSk9RTEY3UmNmb1RKUzdlMUhSV05RWlptYTJEa0E=
kind: Secret
metadata:
  name: demarca-secrets
type: Opaque
